# Generated by Django 6.0.5 on 2026-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinquiry",
            name="budget_scope",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="contactinquiry",
            name="company",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="contactinquiry",
            name="job_title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="contactinquiry",
            name="project_domain",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
