# Generated by Django 6.0.5 on 2026-05-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contactinquiry_budget_scope_contactinquiry_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        help_text="e.g. INTERNSHIP, FULL-TIME, PART-TIME, CONTRACT",
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g. Aug 2025 - Jan 2026 (6 mos)", max_length=150
                    ),
                ),
                ("desc", models.TextField()),
                (
                    "tech",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated values, e.g. Python, Docker, AWS",
                        max_length=300,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order in which it is displayed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=150)),
                ("desc", models.TextField()),
                (
                    "tech",
                    models.CharField(
                        help_text="Comma-separated values, e.g. React, Django, Docker",
                        max_length=300,
                    ),
                ),
                ("link", models.CharField(blank=True, default="#", max_length=300)),
                ("github", models.CharField(blank=True, default="#", max_length=300)),
                (
                    "video_link",
                    models.CharField(
                        blank=True,
                        help_text="Direct link to a demo video (mp4, YouTube, etc.)",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order in which it is displayed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
