# Generated by Django 6.0.5 on 2026-05-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_experience_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilestats",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
