# Generated by Django 6.0.5 on 2026-05-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profilestats_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to True to make this the active CV/resume downloaded from the site.",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resume/CV",
                "verbose_name_plural": "Resume/CVs",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
